import java.util.ArrayList;
/**
 * @author Jaewook Lee, Daniel Hooks
 * @version 12/9/18
 */
/**
 * <h1>Drone</h1> Represents a Drone
 */

public class Drone extends Vehicle implements Profitable {

    final private double GAS_RATE = 1.33;
     /**
     * Default Contructor 
     */
    //============================================================================
    public Drone() {
        
    }
    
    //============================================================================

    /**
     * Constructor
     * 
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Drone(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }
    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */
    /**
     * Returns the profits generated by the packages currently in the Truck.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.33)
     * </p>
     */
    @Override
    public double getProfit() {
    	double summation = 0;
        for (int i = 0; i < getPackages().size(); i++) {
            summation += getPackages().get(i).getPrice();
        }
    	return summation - (getMaximumRange() * GAS_RATE);
    }

    /**
     * Generates a String of the Drone report. Drone report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     * 
     * @return Truck Report
     */
    @Override
    public String report() {
        return "==========Drone Report==========\n" +
                "License Plate No.: " + super.getLicensePlate() + '\n' +
                "Destination: " + super.getZipDest() + "\n" +
                "Weight Load: " + super.getCurrentWeight() + "/" + super.getMaxWeight() + "\n" +
                "Net Profit: " + getProfit() + "\n" +
                "==============================";
    }
    
   

}
